name: CI/CD Pipeline for Login App

# 触发条件：当推送代码到 main 分支时运行
on:
  push:
    branches:
      - main

# 定义作业
jobs:
  build-and-test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - run: echo "构建在自托管运行器上运行"
      
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          timeout-minutes: 10  # 增加超时时间
        env:
          GIT_HTTP_VERSION: 1.1  # 强制使用 HTTP/1.1

      # 2. 手动安装 Node.js（如果无法访问公网）
      - name: Set up Node.js
        uses: actions/setup-node@v4  # 使用最新版本


      # 5. 安装依赖（使用 pnpm）
      - name: Install dependencies
        run: pnpm install --fetch-timeout 600000 --fetch-retries 5

      # 7. 安装 Cypress 所需的图形依赖
      # - name: Install Cypress dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #       libatk1.0-0 \
      #       libgtk-3-0 \
      #       libgbm1 \
      #       libnss3 \
      #       libxss1 \
      #       libasound2 \
      #       libxtst6 \
      #       libatk-bridge2.0-0 \
      #       libx11-xcb1 \
      #       libxcomposite1 \
      #       libxcursor1 \
      #       libxdamage1 \
      #       libxfixes3 \
      #       libxi6 \
      #       libxrandr2 \
      #       libxrender1 \
      #       libfontconfig1 \
      #       libfreetype6

      # 8. 安装 Cypress 二进制文件
      - name: Install Cypress binary
        run: pnpm exec cypress install

      # 9. 启动服务器
      - name: Start server
        run: |
          node server.js &
          sleep 5  # 等待服务器启动（根据需要调整时间）
          curl -s http://localhost:8080/login.html > /dev/null || { echo "Server failed to start"; exit 1; }

      # 10. 运行 Cypress 测试
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/login.cy.js  # 你的测试文件
          browser: chrome
          headed: false  # 强制使用无头模式

      # 11. 缓存 pnpm 依赖（加速后续运行）
      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            /home/runner/.cache/Cypress  # 添加 Cypress 二进制缓存路径
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  deploy:
    needs: build-and-test  # 确保测试通过后才部署
    runs-on: [self-hosted, linux]  # 假设部署也在自托管运行器上运行

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 SSH 密钥（用于连接目标服务器）
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # 从 GitHub Secrets 获取 SSH 私钥
          known_hosts: ${{ secrets.KNOWN_HOSTS }}  # 目标服务器的已知主机

      # 3. 部署到目标服务器
      - name: Deploy to VM
        run: |
          echo "Starting deployment to target server..."
          # 复制代码到目标服务器
          scp -r ./public ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/test-demo/public || { echo "SCP public directory failed"; exit 1; }
          scp ./server.js ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/test-demo/server.js || { echo "SCP server.js failed"; exit 1; }
          scp ./package.json ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/test-demo/package.json || { echo "SCP package.json failed"; exit 1; }
          scp pnpm-lock.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/test-demo/pnpm-lock.yaml || { echo "SCP pnpm-lock.yaml failed"; exit 1; }

          # 在目标服务器上执行部署脚本
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            echo 'Starting deployment on remote server...'
            cd /var/www/test-demo || { echo 'Directory not found'; exit 1; }

            # 安装 pnpm（如果未安装）
            if ! command -v pnpm &> /dev/null; then
              curl -fsSL https://get.pnpm.io/install.sh | sh - || { echo 'Failed to install pnpm'; exit 1; }
              source ~/.bashrc
            fi

            # 安装依赖
            pnpm install --fetch-timeout 600000 --fetch-retries 5 || { echo 'Failed to install dependencies'; exit 1; }

            # 安装 pm2（如果未安装）
            if ! command -v pm2 &> /dev/null; then
              pnpm install pm2 -g || { echo 'Failed to install pm2'; exit 1; }
            fi

            # 启动或重启服务器
            pm2 start server.js || pm2 restart server.js || { echo 'Failed to start/restart server'; exit 1; }
            pm2 save || { echo 'Failed to save pm2 configuration'; exit 1; }
          "
          echo "Deployment completed successfully."